"use client";

import { useState, useTransition } from "react";
import { generateAiReviewAction } from "./actions";

export function AiReview({ gameId, configured }: { gameId: string; configured: boolean }) {
  const [review, setReview] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();

  if (!configured) {
    return (
      <p className="text-xs text-slate-500">
        AI match reviews are available once an Anthropic API key is configured on the server
        (<code className="text-slate-600">ANTHROPIC_API_KEY</code>).
      </p>
    );
  }

  const generate = () => {
    setError(null);
    startTransition(async () => {
      const res = await generateAiReviewAction(gameId);
      if (res.ok) setReview(res.review);
      else setError(res.message || "Couldn't generate a review right now.");
    });
  };

  if (review) {
    return (
      <div className="fade-up">
        <p className="whitespace-pre-line text-sm leading-relaxed text-slate-800">{review}</p>
        <p className="mt-3 text-[11px] text-slate-500">Generated by Claude · always double-check the numbers</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-start gap-2">
      <p className="text-sm text-slate-600">
        Get a coach&apos;s read of this match from AI — it studies every visit, the finishing, and suggests what to
        practise.
      </p>
      <button type="button" className="btn-primary text-sm" onClick={generate} disabled={pending}>
        {pending ? "Studying the scoresheet…" : "✨ Generate AI review"}
      </button>
      {error && <p className="text-sm text-red-600">{error}</p>}
    </div>
  );
}
