"use client";

import { useEffect, useRef, useState } from "react";
import { generateSeasonAiSummaryAction } from "./actions";

export function SeasonAiSummary({
  seasonId,
  configured,
  completedFixtures,
  initialSummary,
  initialAt,
  initialFixtures
}: {
  seasonId: string;
  configured: boolean;
  /** Completed fixtures right now — the summary's freshness fingerprint. */
  completedFixtures: number;
  initialSummary: string | null;
  initialAt: string | null;
  /** Completed-fixture count the stored summary was generated at. */
  initialFixtures: number | null;
}) {
  const [summary, setSummary] = useState<string | null>(initialSummary);
  const [coversFixtures, setCoversFixtures] = useState<number | null>(initialFixtures);
  const [at, setAt] = useState<string | null>(initialAt);
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const triggered = useRef(false);

  // The summary is stale when another fixture has completed since it was made.
  const stale = summary === null || coversFixtures !== completedFixtures;

  useEffect(() => {
    if (!configured || completedFixtures === 0 || !stale || triggered.current) return;
    triggered.current = true;
    setPending(true);
    setError(null);
    generateSeasonAiSummaryAction(seasonId)
      .then((res) => {
        if (res.ok) {
          setSummary(res.summary);
          setCoversFixtures(res.fixtures);
          setAt(res.at);
        } else if (res.reason !== "no_data") {
          setError(res.message || "Couldn't refresh the season summary right now.");
        }
      })
      .finally(() => setPending(false));
  }, [configured, completedFixtures, stale, seasonId]);

  if (!configured && !summary) {
    return (
      <p className="text-xs text-slate-500">
        The AI season summary appears once an Anthropic API key is configured on the server
        (<code className="text-slate-600">ANTHROPIC_API_KEY</code>).
      </p>
    );
  }

  if (completedFixtures === 0 && !summary) {
    return (
      <p className="text-sm text-slate-600">
        The AI season summary will appear here once the first fixture of the season is complete, then refresh
        after every fixture.
      </p>
    );
  }

  return (
    <div className="fade-up">
      {summary && (
        <p className="whitespace-pre-line text-sm leading-relaxed text-slate-800">{summary}</p>
      )}
      {pending && (
        <p className={`text-sm text-slate-500 ${summary ? "mt-3" : ""}`}>
          {summary ? "Refreshing after the latest fixture…" : "Analysing the season so far…"}
        </p>
      )}
      {error && <p className="mt-2 text-sm text-red-600">{error}</p>}
      {summary && !pending && (
        <p className="mt-3 text-[11px] text-slate-500">
          Generated by Claude · season so far ({coversFixtures} fixture{coversFixtures === 1 ? "" : "s"})
          {at ? ` · updated ${new Date(at).toLocaleDateString()}` : ""} · always double-check the numbers
        </p>
      )}
    </div>
  );
}
